PUT http://localhost:3001/api/courses/67d2b53a08e8ad3dddcf8a43
Content-Type: application/json

{
    "name": "Test course",
    "code": "123465A",
    "credits": 5,
    "grade": "5",
    "status": "completed"
}
